"""add_knowledge_item_status_fields

Revision ID: 2754e0bbad53
Revises: 83343105d60b
Create Date: 2025-08-30 01:49:38.780609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2754e0bbad53'
down_revision: Union[str, Sequence[str], None] = '83343105d60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('knowledge_items', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('knowledge_items', sa.Column('task_id', sa.String(), nullable=True))
    op.add_column('knowledge_items', sa.Column('processed_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_items', 'processed_at')
    op.drop_column('knowledge_items', 'task_id')
    op.drop_column('knowledge_items', 'embedding_model')
    op.drop_column('knowledge_items', 'processing_status')
    # ### end Alembic commands ###
