"""created_at added all tables

Revision ID: 7ec8d141360f
Revises: d9a2e02dc99c
Create Date: 2025-08-30 19:11:43.331674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec8d141360f'
down_revision: Union[str, Sequence[str], None] = 'd9a2e02dc99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('scraped_content', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'created_at')
    op.drop_column('scraped_content', 'created_at')
    op.drop_column('knowledge_items', 'created_at')
    # ### end Alembic commands ###
