"""video updated

Revision ID: 83343105d60b
Revises: a216187ac496
Create Date: 2025-08-29 18:49:25.167287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83343105d60b'
down_revision: Union[str, Sequence[str], None] = 'a216187ac496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('processed_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processed_at')
    op.drop_column('videos', 'processing_status')
    # ### end Alembic commands ###
