"""prompt context added to project

Revision ID: 87dacc22b37a
Revises: 7ec8d141360f
Create Date: 2025-08-31 18:09:16.761466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dacc22b37a'
down_revision: Union[str, Sequence[str], None] = '7ec8d141360f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('prompt_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'prompt_context')
    # ### end Alembic commands ###
