"""video channel name added

Revision ID: d9a2e02dc99c
Revises: 2754e0bbad53
Create Date: 2025-08-30 18:01:24.767011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a2e02dc99c'
down_revision: Union[str, Sequence[str], None] = '2754e0bbad53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'channel_id')
    op.drop_column('videos', 'channel')
    # ### end Alembic commands ###
