"""ScrapedContent model dropped

Revision ID: e3fb670ce2e1
Revises: 384c2d23ea4c
Create Date: 2025-09-02 19:24:52.826173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fb670ce2e1'
down_revision: Union[str, Sequence[str], None] = '384c2d23ea4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_content_id'), table_name='scraped_content')
    op.drop_index(op.f('ix_scraped_content_url'), table_name='scraped_content')
    op.drop_table('scraped_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_content',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scraped_content_pkey'))
    )
    op.create_index(op.f('ix_scraped_content_url'), 'scraped_content', ['url'], unique=True)
    op.create_index(op.f('ix_scraped_content_id'), 'scraped_content', ['id'], unique=False)
    # ### end Alembic commands ###
